flights_iceberg:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: dbt
      host: trino
      port: 8080
      database: iceberg
      schema: flights
      threads: 1