name: dbt CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'flight_dbt/**'

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: flight_db
          POSTGRES_USER: user_1
          POSTGRES_PASSWORD: password_1
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DBT_TARGET: ci
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: user_1
      POSTGRES_PASSWORD: password_1
      POSTGRES_DB: flight_db

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt
        run: pip install dbt-postgres

      - name: dbt deps
        working-directory: flight_dbt
        run: dbt deps

      - name: dbt seed
        working-directory: flight_dbt
        run: dbt seed --target ci --profiles-dir .

      - name: dbt parse
        working-directory: flight_dbt
        run: dbt parse

      - name: dbt compile
        working-directory: flight_dbt
        run: dbt compile --profiles-dir .

      - name: dbt build
        working-directory: flight_dbt
        run: dbt build --target ci --profiles-dir . --select stg_aerodatabox_arrivals stg_aerodatabox_departures